# This file configures the analyzer for the example project.
# Inherits from the parent project's flattened analysis options.
# https://dart.dev/guides/language/analysis-options

include: ../analysis_options.yaml
