# cspell: ignore ktlint tearoffs interps setstate WCAG listview inlines datetimes initstate maybeof mediaquery singlechildscrollview scrollview expando futureor vsync firestore scrollables sizedbox
#
# saropa_lints ^1.5.1 - 628+ lint rules for Flutter and Dart
# https://pub.dev/packages/saropa_lints/changelog
#
# Configuration optimized for: DART UTILITY LIBRARY (not a Flutter app)

analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "**/*.bak"
    - "**/*.old"
    - ".crashlytics/**"
    - ".dart_tool/**"
    - ".dev/**"
    - ".github/**"
    - ".idea/**"
    - ".vs/**"
    - ".vscode/**"
    - "bin/cache/**"
    - "build/**"
    - "scripts/**"
    - "example/**"
    - "test/.test_coverage.dart"
    - "android/**"
    - "ios/**"
    - "dependency_overrides/**"
    - "assets/**"
    - "ktlint"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    cast_nullable_to_non_nullable: warning
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
    parameter_assignments: warning
    todo: ignore

  strong-mode:
    implicit-dynamic: false
    implicit-casts: false

formatter:
  page_width: 100
  trailing_commas: preserve

# =============================================================================
# SAROPA LINTS - UTILITY LIBRARY CONFIG
# =============================================================================
# Using 'insanity' tier (ALL 500+ rules enabled).
# Disabling rules that don't apply to this Dart utility library (no Flutter).
# =============================================================================

custom_lint:
  enable_all_lint_rules: true # Enable all saropa_lints rules (insanity tier)
  rules:
    - always_fail_test_case: false # Is used only for testing
    - prefer_double_quotes: false # opinionated: we want Single quote style

    - prefer_trailing_comma_always: false # opinionated
    - prefer_flat_imports: false # opinionated
    - prefer_single_exit_point: false # opinionated
    - prefer_blank_line_after_declarations: false # opinionated
    - prefer_sentence_case_comments: false # opinionated
    - prefer_named_imports: false # opinionated
    - prefer_relative_imports: false # opinionated
    - prefer_var_over_explicit_type: false # opinionated
    - prefer_compact_class_members: false # opinionated
    - prefer_no_blank_line_before_return: false # opinionated
    - prefer_compact_declarations: false # opinionated
    - prefer_explicit_null_assignment: false # opinionated

    # =========================================================================
    # DISABLED - Conflicting rules
    # =========================================================================
    - avoid_inferrable_type_arguments: false # Conflicts with prefer_explicit_type_arguments

    # =========================================================================
    # DISABLED - Too noisy for this project
    # =========================================================================
    - avoid_null_assertion: false # Common in extensions
    - require_future_error_handling: false # Verbose for utility methods

    # =========================================================================
    # DISABLED - Essential tier rules not applicable (no Flutter widgets)
    # =========================================================================
    - require_dispose: false
    - dispose_fields: false
    - require_animation_disposal: false
    - avoid_undisposed_instances: false
    - require_value_notifier_dispose: false
    - require_scroll_controller_dispose: false
    - require_focus_node_dispose: false
    - require_bloc_close: false
    - require_timer_cancellation: false
    - avoid_unassigned_stream_subscriptions: false
    - require_stream_controller_dispose: false
    - always_remove_listener: false
    - avoid_context_in_initstate_dispose: false
    - avoid_inherited_widget_in_initstate: false
    - avoid_build_context_in_providers: false
    - avoid_unsafe_setstate: false
    - use_setstate_synchronously: false
    - avoid_recursive_widget_calls: false
    - require_mounted_check: false
    - avoid_global_key_in_build: false
    - pass_existing_future_to_future_builder: false
    - pass_existing_stream_to_stream_builder: false
    - avoid_duplicate_widget_keys: false
    - avoid_mounted_in_setstate: false
    - avoid_nested_scaffolds: false
    - avoid_multiple_material_apps: false
    - require_vsync_mixin: false
    - require_animation_controller_dispose: false
    - avoid_hidden_interactive: false
    - require_unknown_route_handler: false
    - avoid_context_after_navigation: false

    # =========================================================================
    # DISABLED - Recommended tier rules not applicable (no Flutter widgets)
    # =========================================================================
    - nullify_after_dispose: false
    - require_auto_dispose: false
    - avoid_expensive_build: false
    - prefer_const_child_widgets: false
    - avoid_listview_without_item_extent: false
    - avoid_shrink_wrap_in_lists: false
    - avoid_mediaquery_in_build: false
    - prefer_dedicated_media_query_method: false
    - avoid_singlechildscrollview_with_column: false
    - avoid_stateful_widget_in_list: false
    - prefer_cached_network_image: false
    - avoid_controller_in_build: false
    - avoid_setstate_in_build: false
    - prefer_const_widgets_in_lists: false
    - require_semantics_label: false
    - avoid_icon_buttons_without_tooltip: false
    - avoid_image_buttons_without_tooltip: false
    - avoid_gesture_only_interactions: false
    - avoid_color_only_indicators: false
    - avoid_small_touch_targets: false
    - avoid_text_scale_factor_ignore: false
    - require_image_semantics: false
    - require_notify_listeners: false
    - avoid_bloc_event_in_constructor: false
    - avoid_provider_recreate: false
    - avoid_animation_in_build: false
    - require_hero_tag_uniqueness: false
    - prefer_secure_random: false
    - require_secure_keyboard: false
    - avoid_firestore_unbounded_query: false
    - avoid_database_in_build: false
    - avoid_deeply_nested_widgets: false
    - avoid_single_child_column_row: false
    - avoid_nested_scrollables: false
    - require_text_overflow_handling: false
    - require_image_error_builder: false
    - avoid_form_without_key: false
    - avoid_uncontrolled_text_field: false
    - avoid_text_scale_factor: false
    - prefer_using_list_view: false
    - avoid_scaffold_messenger_after_await: false
    - avoid_empty_setstate: false
    - avoid_unnecessary_setstate: false
    - avoid_stateless_widget_initialized_fields: false
    - avoid_state_constructors: false
    - avoid_empty_text_widgets: false
    - prefer_sized_box_for_whitespace: false
    - prefer_inkwell_over_gesture: false
    - prefer_listview_builder: false
    - avoid_opacity_animation: false
    - prefer_spacing_over_sizedbox: false
    - avoid_material2_fallback: false

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_pub_dependencies: false
